package hr.fer.zemris.bf.model;

/**
 * A node visitor. It visits the nodes of a tree generated by the
 * {@link Parser}.
 *
 * @author Alen Magdić
 *
 */
public interface NodeVisitor {
	/**
	 * Visits the specified constant node.
	 *
	 * @param node
	 *            constant node
	 */
	void visit(ConstantNode node);

	/**
	 * Visits the specified variable node.
	 *
	 * @param node
	 *            variable node
	 */
	void visit(VariableNode node);

	/**
	 * Visits the specified unary operator node.
	 *
	 * @param node
	 *            unary operator node
	 */
	void visit(UnaryOperatorNode node);

	/**
	 * Visits the specified binary operator node.
	 *
	 * @param node
	 *            binary operator node
	 */
	void visit(BinaryOperatorNode node);
}
